### ISSUE TITLE
Multiple routers

### ISSUE THREAD

**Issue by shailsharma** [pedronauck/micro-router#17]
How to configure & use multiple routers?

```
const router1 = router(
  get('/hello/:who', hello)
);
```

```
const router2 = router(
  get('/hello1/:testing', testingFn)
)
```

**Comment by pedronauck** [comment]
So, I trying to figure out what you can do. Why do you have two same routes with different handlers? 

I think that each microservice can have just one router, if you want to have two routers for an one microservice, you need to split it.

**Comment by shailsharma** [comment]
ohh sorry. updated the snippet.

**Comment by pedronauck** [comment]
You can do like shows [here](https://github.com/pedronauck/micro-router#--usage)
