### ISSUE TITLE
Dist is out of date

### ISSUE THREAD

**Issue by novemberborn** [pedronauck/micro-router#20]
Hey! This looks like a neat router library, but unfortunately `dist/index.js` was last updated on May 11th, despite the more recent feature releases.

I'd recommend doing the compilation in a prerelease script, rather than committing it.

Alternatively you could consider requiring Node.js 8, in which case no precompilation is required.

**Comment by pedronauck** [comment]
Thank's @novemberborn, I totally forgot about update the `dist` files

Please, upgrade to the new [v2.2.1](https://github.com/pedronauck/micro-router/releases/tag/v2.2.1) that as a updated bundle :pray:

**Comment by novemberborn** [comment]
Lovely, thanks!
