### ISSUE TITLE
Support nested router

### ISSUE THREAD

**Issue by viztor** [pedronauck/micro-router#30]
want to have something like
const api1 = router(
  '/', someendpoint
)
router(
'api/v1', api1,
'api/v2', api2
)

**Comment by pedronauck** [comment]
That's a pretty good idea, I'll see what I can do about that.

**Comment by paulogdm** [comment]
Oh man that would be so great! Right now I'm simply doing a dirty job like this:
```
if(req.method == '...'){
    if(req.url == )...
} else if(req.method == '...'){
    if(req.url == )...
}
```

**Comment by ppot** [comment]
After some time I build local an implementation of nesting router. PR comping.

**Comment by pedronauck** [comment]
Sorry the to earlier update... in the new release you can use [withNamespace](https://github.com/pedronauck/micro-router#namespaced-routes) function to create something like nested routes :v:

**Comment by ppot** [comment]
withNamespace should support Hier Order. 

let say: 
```
const api = withNamespace('/v1')
const affiliate = withNamespace('/affiliate')

  api(
     affiliate(
         post('/affiliation', affiliation)
         get('/dashboard', dashboard)
     )
  )
```
instead of 

```
const api = withNamespace('/v1')

  api(
     post('/affiliate/affiliation', affiliation)
     get('/affiliate/dashboard', dashboard)
  )
```

@pedronauck
