### ISSUE TITLE
Support passing options to `url-pattern`

### ISSUE THREAD

**Issue by kevva** [pedronauck/micro-router#37]
I have a use case where I want to match everything after a certain path, but `micro-router` only lets me match [certain characters](https://github.com/pedronauck/micro-router/blob/04bdeaf28ec48803ceab13fabfc74fbd6f6958e9/utils/index.js#L5), so instead I have to use a regex like this:

```js
get(/^\/foo\/([^]*)$/, req => {
	const [match] = req.params;
	console.log(match);
	//=> whatever/requested.jpg
});
```

I would like to be able to name my capture groups like [this](https://github.com/snd/url-pattern#make-pattern-from-regex) and also have the ability to define the options sent to `url-pattern`.

**Comment by pedronauck** [comment]
In the new release you can do that passing the [path argument as a UrlPattern](https://github.com/pedronauck/micro-router#urlpattern-instance-as-path) instance

**Comment by kevva** [comment]
Sweet, thanks!
