### ISSUE TITLE
3.1 missing "utils/" when npm install

### ISSUE THREAD

**Issue by jchbh-duplicate** [pedronauck/micro-router#38]
![10341520289356_ pic_hd](https://user-images.githubusercontent.com/785571/37003760-85d08b6a-20a4-11e8-97ad-0d4178e2c760.jpg)

After npm i, there is no utils in path, app will crash when loading.

**Comment by pedronauck** [comment]
Thanks @jchbh-duplicate for the tip, I release a new version fixing that :pray:
