### ISSUE TITLE
ES6 named import for `delete` under Standard

### ISSUE THREAD

**Issue by jda0** [pedronauck/micro-router#7]
It appears impossible to require the `delete` method without upsetting Standard JS, either due to conflicting with a reserved word (`const { delete } = require('microrouter')`) or not defining the function (`require('microrouter')`). Any suggestions?

**Comment by pedronauck** [comment]
Hi jdao, you can do something like that:

```js
const { delete: del } = require('microrouter');
```

**Comment by lucasbento** [comment]
WebStorm also highlights this differently because of the name, perhaps it would be better to export it as `del` as well.

**Comment by pedronauck** [comment]
That's a good point @lucasbento, I'll make this change
