### ISSUE TITLE
Consider using promises instead of async/await to remove the need of node 7.x

### ISSUE THREAD

**Issue by lucasbento** [pedronauck/micro-router#9]
The code base uses one single `await` statement, it must be considered to use promises instead of it so the users can use the package with node LTS (currently 6.10).

Made this change here: https://github.com/entria/micro-router, would be happy to send a PR.

**Comment by pedronauck** [comment]
I made a comment on your pr @lucasbento. If you do that changes I can approve your pr and release a new version!

**Comment by lucasbento** [comment]
@pedronauck: already fixed it, gonna open a PR soon.
